ecomuser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('klog.urls'))
]

klog/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static


from klog.models import Cartitems
from . import views 
app_name = 'klog'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup',views.signup, name="signup"),
    path('login',views.login,name="login"),
    path('logout',views.Logout,name='logout'),
    path('cart',views.cart,name='cart'),
    path('<int:category_id>/item/<int:product_id>/', views.detail, name='detail'),
    path('<int:product_id>/cartdelete',views.cartdelete,name='cartdelete'),
    path('<int:category_id>/item/<int:product_id>/', views.detail, name='detail'),
    path('item-added/<int:product_id>/', views.add_to_cart, name='item-added'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
	url(r'^remove/(?P<product_id>\d+)/$', views.cartdelete, name='cart_remove'),
    path('cartitems',views.cartitems,name='cartitems'),
    path('<int:id>/', views.checkout, name='checkout'),
    url(r'^create/$', views.order_create, name='order_create'),
    path('payment',views.payment,name='payment'),
    
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <title>E-commerce Website</title>
 <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
 <!-- Default theme -->
 <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
  <style>
    nav{
      background-color: green;
    }
    .one-edge-shadow {
              box-shadow: 0 8px 2px -5px rgb(246, 245, 245);
}
.display-8{
  font-weight: 200;
  font-size: 30px;
  font-colour: $teal-200;
}
.button {
  display: inline-block;
  border-radius: 4px;
  background-color: #64eb52;
  border: none;
  color: #FFFFFF;
  text-align: initial;
  font-size: 15px;
  padding: 20px;
  width: 200px;
  transition: all 0.5s;
  cursor: pointer;
  margin: 5px;
}

.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -10px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 10px;
}
</style>
</head>

<body>
  <!-- navbar -->
  
<nav class="one-edge-shadow
  navbar navbar-light
  sticky-top navbar 
  navbar-expand-lg
  text-white">
    <a class="navbar-brand ms-3 text-dark " href="/">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">

    <img src="https://www.freepnglogos.com/uploads/shopping-cart-png/shopping-cart-svg-png-icon-download-28.png" style="width:50px;height:50px,color:text-light;">E-Commerce</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/store">Store <span class="sr-only">(current)</span></a>
        </li>

          </ul>




      <ul class=" navbar-nav my-2 my-lg-0">
        <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
        <script>
          alertify.set('notifier','position', 'top-right');
          {% for msg in messages %}
          alertify.success('{{msg}}');
    
          {% endfor %}
    
        </script>

        <li class="nav-item active">
          <a class="nav-link" href="/cart">Cart 
            <span class="badge badge-success">{{request.session.cart.keys|length}}</span>
            <span class="sr-only">(current)</span></a>
        </li>

        {% if request.session.customer %}
        
        <li class="nav-item active ">
          <a class="nav-link" href="/orders">Orders<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active ">
          <a class="nav-link" href="/logout">Logout<span class="sr-only">(current)</span></a>
        </li>
        {% else %}
       
        <li class="nav-item active">
          <a class="nav-link" href="/signup">Signup<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/login">Login<span class="sr-only">(current)</span></a>
        </li>
        {% endif %}


      </ul>


    </div>
  </nav>
  <!---->
  {% block content %}{% endblock %}
  {% comment %} Jquery {% endcomment %}
  <script src="{% static '/js/jquery-3.6.0.min.js' %}"></script>
  <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

  <script src="{% static '/js/custom.js' %}"></script>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdn.datatables.net/1.11.3/css/jquery.dataTables.min.css"></script>
  <script src="https://cdn.datatables.net/1.11.3/js/jquery.dataTables.min.js"></script>
  <script src="https://cdn.datatables.net/1.11.3/js/dataTables.bootstrap4.min.js"></script>
  

</html>

templates/cart.html
{% extends 'base.html' %}

{% block title %}
Shopping Cart
{% endblock %}

{% block content %}
<li>Here is your shopping cart so far</li>


{% if products %}
    {% for product in products %}
        <li>
            <a href="{% url 'klog:detail' product.category.id product.id %}">
                <img src="/shop/{{ product.image }}" alt="{{ product.product_name }}" width="300">
            </a>
            <br>
            <a href="{% url 'klog:detail' product.category.id product.id %}">{{ product.name }}</a>
           price:
            <strong>{{ product.price }} &#8377;</strong>
            -- {{ product.category}}
           
            <br>
            <td>
                
                <form action="{% url "klog:cart_add" product.id %}" method="post">
                    {% csrf_token %}
                    {{ product.update_quantity_form.quantity }}
                    {{product.update_quantity_form.update }}
                    <input type="submit" value="Update" class="btn btn-info">
                </form>
            </td>
            
            <button class="button" style="vertical-align:middle"><a href="{% url 'klog:cartdelete' product.id %}"><span>Remove item from cart</span></a></button>
        </li>
    {% endfor %}
<h2>Total: {{ total }} &#8377;</h2>


<h3>To procceed to checkout </h3>
<p class="text-left">
    <a href="{% url 'klog:index' %}" class="btn btn-default">Continue Shopping</a>
    <a href="{% url 'klog:order_create' %}" class="btn btn-primary">Checkout</a>
</p>

    

{% else %}
    You don't have any items yet
{% endif %}
<script src="{% "

{% endblock %}

templates/cartdelete.html
{% extends 'base.html' %}

{% block title %}
You've deleted item from cart!
{% endblock %}
{% block content %}
<h2>The {{ product.name }} is no more in your shopping cart</h2>
{% endblock %}

templates/cartitems.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <h1>Your shopping cart</h1>
  <table class="table">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td><a href="{% url  'cart_remove' product.id %}">Remove</a></td>
            <td class="num">R{{ item.price }}</td>
            <td class="num">R{{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">R{{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'index'%}" class="button light">Continue shopping</a>
    <a href="#" class="button">Checkout</a>
  </p>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}

{% block title %}
Success!
{% endblock %}
{% block content %}
<h1>Thank you for your Order!
<br>Your order number: <strong>{{ order_id }}</strong></h1>
<h2>You've ordered:</h2>
{% for product in products %}
<li>{{ product.product_name }}
    <img src="/shop//{{ product.image }}" alt="{{ product.name }}" width="300">
</li>
{% endfor %}
{% endblock %}

templates/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Your Shopping Cart| Checkout
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row" style="margin-top: 6%">
            <div class="col-md-8">
                <h4 class="page-header">Checkout</h4>
                <form action="." method="post">
                    {% csrf_token %}
                    {{ form.as_p }}<br>
                    <input type="submit" class="btn btn-primary" value="Continue">
                </form>
            </div>
            <div class="col-md-4">
                <div class="page-header">
                    Your Order
                </div>
                <ul class="list-group">
                    {% for item in cart %}
                        <li class="list-group-item">
                        {{ item.quantity }}x {{ item.product.name }}
                        <span>Kshs. {{ item.total_price }}</span>
                        </li>
                    {% endfor %}

                <li class="list-group-item active">Total Cost: {{total}}</li>
                </ul>

            </div>
        </div>
    </div>
{% endblock %}


templates/detail.html
{% extends 'base.html' %}

{% block title %}
View detail on product
{% endblock %}
{% block content %}

<h2>{{ product.name }}</h2>
<br>
<img src="/shop/{{ produc.image }}" alt="{{ produc.product_name }}" width="300">
<br><p>{{ produc.disc }}</p>
{% if produc.quantity > 0 %}
	<label class="badge bg-success">In stock</label>
{% else %}
	<label class="badge bg-danger">Out of stock</label>
{% endif %}
<div class="row mt-2 product_data">
	<div class="col-md-3">
        {% csrf_token %}
        <input type="hidden" value="{{ product.id}}" class="prod_id">
		<label for="Quantity">Quantity</label>
		<div class="input-group text-center mb-3" style="width:130px;">
            <button class="input-group-text decrement-btn">-</button>
            <input type="text" name="quantity" class="form-control qty-input text-center" value="1">
            <button class="input-group-text increment-btn">+</button>
        </div>
	</div>
    <div class="col-md-9">
        <br/>
        
        
    </div>
</div>
<h3>{{ produc.price }} &euro;</h3><button><h2><a href="/item-added/{{ product_id }}">Add to cart</a></h2></button>

{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<title>products</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="Your description">
<meta name="keywords" content="Your keywords">
<meta name="author" content="Your name">
<link rel="icon" href="images/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />

<link rel="stylesheet" href="{%static 'css/bootstrap.css' %}" type="text/css" media="screen">
<link rel="stylesheet" href="{%static 'css/bootstrap-responsive.css' %}" type="text/css" media="screen">    
<link rel="stylesheet" href="{%static 'css/style.css' %}" type="text/css" media="screen">
<link rel="stylesheet" href="{%static 'css/camera.css' %}" type="text/css" media="screen">
<link rel="stylesheet" href="{%static 'css/touchTouch.css' %}" type="text/css" media="screen">
<link rel="stylesheet" href="{%static 'css/isotope.css' %}" type="text/css" media="screen">


<script type="text/javascript" src="{%static 'js/jquery.js' %}"></script>  
<script type="text/javascript" src="{%static 'js/jquery.easing.1.3.js' %}"></script>
<script type="text/javascript" src="{%static 'js/superfish.js' %}"></script>

<script type="text/javascript" src="{%static 'js/jquery.ui.totop.js' %}"></script>
<script type="text/javascript" src="{%static 'js/camera.js' %}"></script>
<script type="text/javascript" src="{%static 'js/jquery.mobile.customized.min.js' %}"></script>

<script type="text/javascript" src="{%static 'js/touchTouch.jquery.js' %}"></script>
<script type="text/javascript" src="{%static 'js/jquery.isotope.min.js' %}"></script>
<script>
$(document).ready(function() {
	/////// icons
	$(".social li").find("a").css({opacity:0.6});
	$(".social li a").hover(function() {
		$(this).stop().animate({opacity:1 }, 400, 'easeOutExpo');		    
	},function(){
	    $(this).stop().animate({opacity:0.6 }, 400, 'easeOutExpo' );		   
	}); 

	// camera
	$('#camera_wrap').camera({
		//thumbnails: true
		autoAdvance			: false,		
		mobileAutoAdvance	: false,
		height: '37%',
		hover: false,
		loader: 'none',
		navigation: false,
		navigationHover: false,
		mobileNavHover: false,
		playPause: false,
		pauseOnClick: false,
		pagination			: false,
		time: 7000,
		transPeriod: 1000,
		minHeight: '300px'
	});

	

}); //
$(window).load(function() {
	// isotop
	var $container = $('#isotope-items'),
		$optionSet = $('#isotope-options'), 
	    $optionSets = $('#isotope-filters'), 
	    $optionLinks = $optionSets.find('a'); 
    $container.isotope({ 
        filter: '*',
        layoutMode: 'fitRows'
    });  
   	$optionLinks.click(function(){ 
   		var $this = $(this); 
    	// don't proceed if already selected 
		if ( $this.hasClass('selected') ) { 
			return false; 
		}    		
   		$optionSet.find('.selected').removeClass('selected'); 
   		$this.addClass('selected');

        var selector = $(this).attr('data-filter'); 
        $container.isotope({ 
            filter: selector            
        }); 
      	return false; 
    });    	
	$(window).on("resize", function( event ) {	
		$container.isotope('reLayout');		
	});		

	// touchTouch
	$('.thumb-isotope .thumbnail a').touchTouch();

}); //
</script>		
<!--[if lt IE 8]>
		<div style='text-align:center'><a href="http://www.microsoft.com/windows/internet-explorer/default.aspx?ocid=ie6_countdown_bannercode"><img src="http://www.theie6countdown.com/images/upgrade.jpg"border="0"alt=""/></a></div>  
	<![endif]-->    

<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>      
  <link rel="stylesheet" href="{%static 'css/ie.css' %}" type="text/css" media="screen">
<![endif]-->
</head>

<body class="subpage">
<div id="main">

<header>
<div class="logo_wrapper"><a href="index.html" class="logo"><img src="{%static 'images/logo.png' %}" alt=""></a></div>	
<div class="top1">
<div class="container">
<div class="row">
<div class="span12">
	<div class="top1_inner clearfix">
		<div class="phone1">Need Help? Call us: <span>1.123.456.7890</span></div>
		<div class="phone2 clearfix">
			<div class="txt1">Follow us:</div>
			<div class="social_wrapper">
				<ul class="social clearfix">
				    <li><a href="#"><img src="{%static 'images/social_ic1.png' %}"></a></li>
				    <li><a href="#"><img src="{%static 'images/social_ic2.png' %}"></a></li>
				    <li><a href="#"><img src="{%static 'images/social_ic3.png' %}"></a></li>			    
				</ul>
			</div>
		</div>
	</div>
</div>	
</div>	
</div>
</div>	
<div class="top2">
<div class="container">
<div class="row">
<div class="span12">
<div class="top2_inner">
<div class="navbar navbar_">
	<div class="navbar-inner navbar-inner_">
		<a class="btn btn-navbar btn-navbar_" data-toggle="collapse" data-target=".nav-collapse_">
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</a>
		<div class="nav-collapse nav-collapse_ collapse">
			<ul class="nav sf-menu clearfix">
				<li><a href="index.html">Home</a></li>
				<li><a href="index-1.html">Company </a></li>				
				<li class="active sub-menu sub-menu-1"><a href="index-2.html">Products<em></em></a>
					<ul>
						<li><a href="index-2.html">About us</a></li>
						<li class="sub-menu sub-menu-2"><a href="index-1.html">History<em></em></a>
							<ul>
								<li><a href="index-2.html">lorem ipsum dolor</a></li>
								<li><a href="index-2.html">sit amet</a></li>
								<li><a href="index-2.html">adipiscing elit</a></li>
								<li><a href="index-2.html">nunc suscipit</a></li>
								<li><a href="404.html">404 page not found</a></li>
							</ul>
						</li>
						<li class="sub-menu sub-menu-2"><a href="index-2.html">Our team<em></em></a>
							<ul>
								<li><a href="index-2.html">lorem ipsum dolor</a></li>
								<li><a href="index-2.html">sit amet</a></li>
								<li><a href="index-2.html">adipiscing elit</a></li>
								<li><a href="index-2.html">nunc suscipit</a></li>									
							</ul>
						</li>
						<li><a href="index-1.html">Media</a></li>						
					</ul>
				</li>
				<li class="sub-menu sub-menu-1"><a href="index-3.html">Services<em></em></a>
					<ul>
						<li><a href="index-3.html">Lorem ipsum dolor</a></li>						
						<li><a href="index-3.html">Sit amet consectetue</a></li>
						<li><a href="index-3.html">Adipiscing elit</a></li>						
						<li><a href="index-3.html">Nunc suscipit</a></li>						
					</ul>						
				</li>
				<li class="nav-item active">
					<a class="nav-link" href="cart">Cart 
						<span class="badge badge-success">{{request.session.cart.keys|length}}</span>
						<span class="sr-only">(current)</span>
					</a>
				</li>												
				<li class="nav-item active">
					<form class ="nav-collapse">
							
						<ul class="nav sf-menu clearfix">
							{% if user %}
							<li class="nav-item active"><a class="nav-link" style="font-weight: bold;">{{user}}</a></li>
							<li><a href="/logout">logout</a></form></li>
							{% else %}
							<li class="nav-item active"><a class="nav-link" href="login">Login</a></li>
							<li class="nav-item active"><a class= "nav-link" href="/signup">Signup</a></li>	
							{% endif %}
						</ul>
							
					</form>
				</li>
			</ul>
		</div>
	</div>	
</div>
</div>
</div>	
</div>	
</div>
</div>
</header>	

<div id="slider" class="clearfix">
<div id="camera_wrap">
	<div data-src="{%static 'images/slide2.jpg' %}"></div>	
</div>	
</div>

<div id="content">
<div id="content2">

<div class="page_title">
<div class="container">
<div class="row">
<div class="span12">
	Gallery
</div>	
</div>	
</div>	
</div>
<div id="inner">
<div id="inner2">
	<div class="container">
<div class="row product_data">	
	<div class="span12">
		<h1>Our Products</h1>           
			<div id="isotope-options">
				<ul id="isotope-filters" class="clearfix">
	
					<li><a href="/" class="selected" >All Products</a></li>
	
					{% for category in categories %}
					<li><a href="/?category={{category.id}}"
						class="list-group-item list-group-item-action btn btn-outline-success ">{{category.cname}}</a></li>
					{% endfor %}
				</ul>
			</div>
					
			<!-- all products -->
			
			{% for product in products %}
            <li class="span3 isotope-element isotope-filter3">
				
				<div class="thumb-isotope">
					
						<div class="thumbnail clearfix">
							
							<a href="{%static 'images/blank.png' %}">
							<figure>
								<img src="{{product.image.url}}" alt=""><em></em>
							</figure>
							</a>
							<div class="caption">
								<div class="txt1">
									<td>{{ forloop.counter }}</td>
									{{product.product_name}}
								</div>
								<div class="txt2">
									{{product.disc}}
									{{product.weight}}gm

								</div>
								<div class="txt3">
									{{product.price}}&#8377;
								</div>
								
								<form action='/' method="POST">
									{% csrf_token %}
									{{ CartAddProductForm }}
									<input type="hidden" name="product" value="{{product.id}}">
									
									
									<button><a href="{% url 'klog:detail' product.category.id product.id %}">Add to cart</a></button>
								</form>
								
							</div>
						</div>
					
				</div>
				
            </li>
			{% endfor %}              
        </ul>
	</div>
</div>
	</div>
</div>	
</div>
	
</div>	
</div>

<footer>
<div class="container">
<div class="row">
<div class="span12">
<div class="bot clearfix">
<div class="bot1">
<div class="menu_bot">
    <ul id="menu_bot" class="clearfix">
      <li><a href="index.html">Home</a></li>
      <li><a href="index-1.html">Company</a></li>
      <li><a href="index-2.html">Services</a></li>
      <li><a href="index-3.html">Products</a></li>
      <li><a href="index-4.html">Solutions</a></li>
      <li><a href="index-5.html">Contacts</a></li>          
    </ul>
</div>
</div>	
<div class="bot2 clearfix">
<div class="search-form-wrapper clearfix">
	<form id="search-form" action="" method="GET" accept-charset="utf-8" class="navbar-form" >
		<input type="text" name="s" value='Search' onBlur="if(this.value=='') this.value='Search'" onFocus="if(this.value =='Search' ) this.value=''">
		<a href="#" onClick="document.getElementById('search-form').submit()"></a>
	</form>
</div>
</div>
</div>
<div class="copyright">Copyright © 2021. All rights reserved.</div>
</div>	
</div>	
</div>		
</footer>








	
</div>
<script type="text/javascript" src="{%static 'js/bootstrap.js' %}"></script>
</body>
</html>

templates/item-added.html
{% extends 'base.html' %}

{% block title %}
You've added item to cart!
{% endblock %}
{% block content %}
{% if produc == None %}
    <h2>You've already had this item in your cart</h2>
{% else %}
    <h2>The {{ produc.product_name }} is now in your shopping cart:</h2>
    <br>
    <img src="/shop/{{ produc.image }}" alt="{{ produc.product_name }}" width="300">
    <br><p>{{ produc.disc|linebreaksbr }}</p>
    <h3>{{ produc.price }} &euro;</h3>
{% endif %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="p-3 m-3">
        <div class="col-lg-5 rounded mx-auto border pt-4">
            <div class="text-center col">
            
                <img
                src="https://th.bing.com/th/id/Rd51d7c0fde6d96a31538a86cbd57f3c0?rik=%2fTJxRkU2V371QQ&riu=http%3a%2f%2ftechnologyend.com%2fwp-content%2fuploads%2f2015%2f11%2fwhy-shop-online.jpg&ehk=v1KiYT0i5U1ABCRueDSdLqnazh2BdlVD89Z4qXE0Kgs%3d&risl=&pid=ImgRaw" alt=""
                class="" style="height: 150px;">
            <hr>
            </div>
            <h3 class="alert alert-light rounded-pill" style="text-align:center" >Login</h3>
            <form id="loginForm">
                {% csrf_token %}
               
                {% if error%}
                <div class="alert alert-danger" role="alert">
                    {{error}}
                </div>
                {% endif %}
           
                <!-- email -->
                <div class="form-group">
                    <label for="">Username</label>
                    <input required type="text" name="username" id="username"
                    value="{{values.email}}" 
                    class=" form-control-sm form-control" placeholder="username">
                </div>


                <!-- password -->
                <div class="form-group">
                    <label for="">Password</label>
                    <input type="password" 
                    name="password" 
                    id="password"
                     class="form-control form-control-sm" >
                </div>

                <!--Checkme button-->
            <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="exampleCheck1">
                    <label class="form-check-label d-grid gap-2" for="exampleCheck1">Check me out</label>
                </div>
                <hr>
                {% if request.GET.next %}
                    <input type="hidden"name="next" value="{{request.GET.next}}">
                {% endif %}

                <button type="submit" class="btn btn-sm btn-success col-lg-12">Login</button>


                
            </form>
        </div>
    </div>
</div>

<script
src="https://code.jquery.com/jquery-3.6.0.js"
integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.3/jquery.validate.js"></script> 

  <script>
    $(document).ready(function() {
      $('#password').blur(function() {
        var password = $(this).val();
        if (password.length == 0){
          $('#err3').show();
        }else if(password.length< 8){
          $('#err1').show();
        }
        else{
          $('#err1').hide();
          $('#err3').hide();
        }
      }), $('#username').blur(function() {
        var username = $(this).val();
        if (username.length == 0){
          $('#err2').show();
        }else{
          $('#err2').hide();
          
        }
      })
      
    })
  </script>
  <script>
    $(document).on('submit','#loginForm',(e)=>{
      e.preventDefault();
      var username = $('#username').val()
      var password = $('#password').val()
      var data = {
          'csrfmiddlewaretoken': '{{csrf_token}}',
          'username': username,
          'password' : password
      }
      $.ajax({
        URL : '/',
        type: 'POST',
        data:data,
        dataType : 'json',
        success:function(data) {
          if(data.success) {
            alert('Login successful')
            window.location.replace('/')
          }else{
            alert('User is unauthenticated')
          }
          
        }
        
    })
      
    })
    </script>
    {% endblock %}